### ISSUE TITLE
Test order should match readme order

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/js-deli-counter#10]
The readme has the functions listed in a different number than the tests go through them. We should match these up to make things clearer for the student. Ideally, we should have the tests run in the order of the readme as I think `currentLine` is the trickiest function.

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.
