### ISSUE TITLE
Glitch?

### ISSUE THREAD

**Issue by pogii** [learn-co-curriculum/js-deli-counter#18]
I'm not sure if it's just my Learn IDE install but I have not had any problems with my IDE until this lesson. The lesson page says that I have passed all tests though I have not. When I type 'learn test' I sometimes see the test error descriptions but I also routinely see the debug stack trace with no test error descriptions shown. This happens even when I haven't changed any code but just want to clear my console window and see the errors again. When I shutdown the IDE and restart it that helps, but then when I leave my computer and it goes to sleep and I resume the lesson, it's back to the problems mentioned above.

**Comment by JessRudder** [comment]
Hi @pogii - the IDE hasn't been an issue for other people on this lab, so it looks like it's not lab related.  If you're still having IDE issues, I'd suggest using the "Ask a Question" feature to talk to a Learn Expert.
