### ISSUE TITLE
Deli Counter: nmp warnings, code not saved

### ISSUE THREAD

**Issue by qtotuan** [learn-co-curriculum/js-deli-counter#28]
This lab has shown bugs throughout. Multiple npm WARN messages every time I tried to run the test. Then the window closed unexpectedly. When I returned, my code was gone ALTHOUGH I saved throughout the process. 
How do I retrieve my code?

**Comment by JessRudder** [comment]
Hi @qtotuan - sorry to hear about your trouble.  I'd suggest using the "Ask a Question" feature to talk to a Learn Expert that can help you debug in real time.  This feature is for issues related to a specific lab, not the IDE.
