### ISSUE TITLE
Remove Solution Branch

### ISSUE THREAD

**Issue by realAndrewCohn** [learn-co-curriculum/js-deli-counter#40]
Considering that we deploy this to potential applicants, I think we should remove the solution branch from this lab

**Comment by DanielSeehausen** [comment]
put up to additional stakeholders to see if we can do this

**Comment by realAndrewCohn** [comment]
Looks like the official answer, https://github.com/learn-co-curriculum/deli-counter/issues/18, is that we want to keep solution. Closing the issue.
