### ISSUE TITLE
lab unsolvable with information provided

### ISSUE THREAD

**Issue by MetaFood** [learn-co-curriculum/js-deli-counter#46]
the solution on github uses .join() but nowhere in any of the js lessons up to this point have used that method so yeah its unsolvable unless we're taught .join() ahead of time, or if we cheat and look up the answer.

**Comment by sgharms** [comment]
Hey @MetaFood 

It seems to me that there's a less-elegant solution that doesn't involve using `join()` nor encourages cheating. We'll add a note though.
