### ISSUE TITLE
Can't connect to Learn.co in IDE. 

### ISSUE THREAD

**Issue by jyang81** [learn-co-curriculum/js-deli-counter#52]
I've restarted several times. When I open IDE, it's just blank. Is the server down?

**Comment by maxwellbenton** [comment]
Hi @jyang81,

Sorry to hear you were having difficulty connecting to Learn. I hope you were able to connect. If you are still working on any Learn lessosn and continue to experience this issue, please reach out to support@learn.co for further assistance.

Thank you!
