### ISSUE TITLE
Test file doesn't seem to import code

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/js-deli-counter#9]
@pletcher The test file doesn't seem to know anything of the functions created in the deli.js file. Solution branch does not work either.

**Comment by pletcher** [comment]
I don't think I can replicate.

![image](https://cloud.githubusercontent.com/assets/2015049/15609822/30fd65fc-23f0-11e6-9cb3-5e9ed83f1adc.png)

What version of `learn-test` and Node.js are you running?

**Comment by aturkewi** [comment]
```
// ♥ learn-test -v
2.3.2
```

**Comment by aturkewi** [comment]
@pletcher are there any other npm packages that may need to be installed to run this test?

**Comment by pletcher** [comment]
I just ran that on a fresh install -- `npm install && npm test` should do it.

**Comment by aturkewi** [comment]
I needed to install the latest version of npm.
```
npm install -g n
n latest
```
Then everything worked.
